// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("8.0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("8.0.0.1")>]
[<assembly: AssemblyCompanyAttribute("IntelliFactory")>]
[<assembly: AssemblyCopyrightAttribute("(c) IntelliFactory 2023")>]
[<assembly: AssemblyTitleAttribute("https://github.com/dotnet-websharper/plotly")>]
[<assembly: AssemblyProductAttribute("WebSharper Plotly")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "8.0.0.0"
    let [<Literal>] AssemblyFileVersion = "8.0.0.1"
    let [<Literal>] AssemblyCompany = "IntelliFactory"
    let [<Literal>] AssemblyCopyright = "(c) IntelliFactory 2023"
    let [<Literal>] AssemblyTitle = "https://github.com/dotnet-websharper/plotly"
    let [<Literal>] AssemblyProduct = "WebSharper Plotly"
