// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("5.0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("5.0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "5.0.0.0"
    let [<Literal>] AssemblyFileVersion = "5.0.0.1"
