// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("6.0.0.0")>]
[<assembly: AssemblyFileVersionAttribute("6.0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "6.0.0.0"
    let [<Literal>] AssemblyFileVersion = "6.0.0.1"
